---
- name: Avi Controller | CSP | Service deploy | Check if service already exists
  uri:
    url: "https://{{ inventory_hostname }}/api/running/services/service/{{ con_csp_service_name }}"
    method: GET
    user: "{{ con_csp_user }}"
    password: "{{ con_csp_password }}"
    force_basic_auth: yes
    headers:
      Accept: '*/*'
    validate_certs: false
    return_content: true
  failed_when: false
  register: con_csp_service_exists
  delegate_to: localhost

- block:
    - set_fact:
        con_csp_service_exists_json: "{{ con_csp_service_exists.content|from_json }}"
    - debug: msg="Service {{ con_csp_service_exists_json['vsb:service'].name }} already exists."
  when: con_csp_service_exists.status == 200

- name: Avi Controller | CSP | Service deploy | Create the service
  uri:
    url: "https://{{ inventory_hostname }}/api/running/services/"
    method: POST
    user: "{{ con_csp_user }}"
    password: "{{ con_csp_password }}"
    force_basic_auth: yes
    headers:
      Accept: '*/*'
    validate_certs: false
    body_format: json
    body:
      service:
        disk_size: "{{ con_csp_disk_size|int }}"
        name: "{{ con_csp_service_name }}"
        power: 'on'
        iso_name: "{{ con_csp_qcow_image_name }}"
        day0_filename: "{{ con_csp_metafile_name }}"
        numcpu: "{{ con_csp_num_cpu|int }}"
        memory: "{{ con_csp_memory_mb|int }}"
        vnics:
          vnic:
            "{{ con_csp_vnics }}"
    return_content: true
  register: con_csp_service
  failed_when: con_csp_service.status != 201
  delegate_to: localhost
  when: con_csp_service_exists.status != 200
